[root]
directory = "/backend"

[build]
builder = "RAILPACK"
watchPatterns = ["/backend/**"]
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "bash start.sh"
healthcheckPath = "/health"
preDeployCommand = ["prisma generate"]
sleepApplication = false
useLegacyStacker = false
ipv6EgressEnabled = false
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig.us-west2]
numReplicas = 1
